FROM python:3.11-slim

WORKDIR /modbus-server


COPY modbus-server/requirements.txt* ./ 
RUN --mount=type=cache,target=/root/.cache/pip \
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

COPY modbus-server/ ./ 

CMD ["python", "server/modbus-server.py"]