FROM python:3.11-slim

WORKDIR /modbus-traffic-gen


COPY modbus-traffic-gen/requirements.txt* ./ 
RUN --mount=type=cache,target=/root/.cache/pip \
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

COPY modbus-traffic-gen/ ./ 

EXPOSE 5020
CMD ["python", "modbus-traffic-gen/traffic_gen.py"]